/** Shared by MCP discovery, tool output and the dashboard documentation. */
export const EDITOR_CONTENT_DESCRIPTION = "Editor.js JSON: {blocks:[{type,data}]}, not a Markdown string. Supports paragraph, header, list, quote, code, table, linkTool, image, raw and delimiter. Call get_editor_guide for exact examples. Tables use data.content as string[][] and data.withHeadings=true for a bold, shaded first row. When supplied to update_posts, content replaces ALL blocks: get_posts first, preserve untouched blocks and their IDs, then submit the complete content.";

export const editorGuide = {
  format: "Use create_posts or update_posts with content: {blocks: [...]}. Blocks appear in array order. The same JSON is editable in the dashboard; no browser interaction is needed.",
  editing: "For existing posts, call get_posts with the internal post ID first. Update only requested fields. Supplying content replaces the entire document, not individual blocks. Preserve all untouched blocks, IDs and tunes. Do not send blogId: the API key determines the blog. Prefer drafts and ask before publishing or modifying live content; publication requires content:publish as well as content:write.",
  inlineFormatting: "In text fields and table cells, use safe HTML such as <strong>, <em>, <code>, <br> and <a href=\"https://example.com\">link</a>. Markdown syntax inside text is not converted. In code blocks, use plain code; it is escaped for public rendering.",
  media: "Use upload_image with media:write to upload a public image, then put the returned URL in image.data.file.url or coverImage. Alternatively use an existing public HTTPS image URL. Never upload confidential files: draft images are public too. The MCP does not generate images or automatically fetch link previews; supply known link metadata without inventing it.",
  rendering: "Public HTML is sanitized for every authoring method. Raw HTML cannot execute scripts, event handlers or arbitrary iframes. Supported block content renders through the same converter as the dashboard. Some editor-only layout tunes do not affect public HTML. Host blogs must load /zenex-cms.css or provide equivalent styles. Prefer heading levels 2–4 inside posts; the public renderer normalizes level 1 to level 2.",
  blocks: [
    { type: "paragraph", description: "Text with safe inline HTML.", example: { type: "paragraph", data: { text: "A paragraph with <strong>bold</strong> and <em>italic</em> text." } } },
    { type: "header", description: "Section heading. The dashboard supports levels 1–4; prefer 2–4 below the post title.", example: { type: "header", data: { text: "Section title", level: 2 } } },
    { type: "list", description: "Unordered or ordered list; nested items use the same {content, meta, items} shape. Use style ordered for numbering.", example: { type: "list", data: { style: "unordered", meta: {}, items: [{ content: "First item", meta: {}, items: [{ content: "Nested item", meta: {}, items: [] }] }] } } },
    { type: "quote", description: "Quotation with optional attribution.", example: { type: "quote", data: { text: "Quoted text.", caption: "Source", alignment: "left" } } },
    { type: "code", description: "Plain code, not executable HTML. Do not HTML-escape it yourself.", example: { type: "code", data: { code: "const answer = 42;" } } },
    { type: "table", description: "Rectangular array of rows. Preserve empty cells as empty strings. Set withHeadings true for a header row, false for only data rows. Safe inline HTML is allowed in cells.", example: { type: "table", data: { withHeadings: true, stretched: false, content: [["Feature", "Status"], ["Tables", "Supported"], ["Notes", ""]] } } },
    { type: "linkTool", description: "Link card. Supply a URL and only verified title/description/image metadata. Metadata is optional.", example: { type: "linkTool", data: { link: "https://example.com", meta: { title: "Example", description: "An example link." } } } },
    { type: "image", description: "Public image URL and optional caption. Use upload_image first when uploading a file.", example: { type: "image", data: { file: { url: "https://example.com/image.jpg" }, caption: "Example image", withBorder: false, withBackground: false, stretched: false } } },
    { type: "raw", description: "Safe HTML only. Scripts, event handlers and arbitrary iframe embeds are removed from public output.", example: { type: "raw", data: { html: "<p><strong>Safe HTML</strong> content.</p>" } } },
    { type: "delimiter", description: "Visual separator between sections.", example: { type: "delimiter", data: {} } },
  ],
};
